import {
  AlertCircle,
  Apple,
  Archive,
  Bell,
  Bike,
  Book,
  BookOpen,
  Bookmark,
  Cake,
  Calendar,
  Camera,
  Car,
  CheckCircle,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Flower2,
  Folder,
  Footprints,
  Frown,
  Gamepad2,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Home,
  Leaf,
  Lightbulb,
  Link,
  LucideIcon,
  Mail,
  MapPin,
  Meh,
  MessageCircle,
  Moon,
  Music,
  Notebook,
  Palette,
  Paperclip,
  PartyPopper,
  Pencil,
  Phone,
  Pill,
  Plane,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  StickyNote,
  Sun,
  Tag,
  Target,
  Train,
  TreePine,
  Trophy,
  Utensils,
  UserCircle,
  Users,
  Video,
  Zap,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  star: Star,
  heart: Heart,
  flame: Flame,
  zap: Zap,
  target: Target,
  trophy: Trophy,
  sparkles: Sparkles,
  gem: Gem,
  book: Book,
  'book-open': BookOpen,
  notebook: Notebook,
  'sticky-note': StickyNote,
  'file-text': FileText,
  clipboard: Clipboard,
  pencil: Pencil,
  'graduation-cap': GraduationCap,
  'message-circle': MessageCircle,
  mail: Mail,
  phone: Phone,
  video: Video,
  users: Users,
  'user-circle': UserCircle,
  home: Home,
  coffee: Coffee,
  utensils: Utensils,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  cake: Cake,
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  apple: Apple,
  pill: Pill,
  stethoscope: Stethoscope,
  music: Music,
  headphones: Headphones,
  'gamepad-2': Gamepad2,
  palette: Palette,
  camera: Camera,
  film: Film,
  car: Car,
  plane: Plane,
  train: Train,
  'map-pin': MapPin,
  globe: Globe,
  compass: Compass,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  leaf: Leaf,
  'flower-2': Flower2,
  'tree-pine': TreePine,
  paperclip: Paperclip,
  link: Link,
  folder: Folder,
  archive: Archive,
  tag: Tag,
  bookmark: Bookmark,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  'party-popper': PartyPopper,
  lightbulb: Lightbulb,
  bell: Bell,
  clock: Clock,
  calendar: Calendar,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
};

export function getIconComponent(iconName: string): LucideIcon {
  return iconMap[iconName] ?? Tag;
}
